azurerm_resource_group = "Gafar-rg"
location = "UK South"
azurerm_virtual_network = "Dev-vnet"
address_space = ["10.0.0.0/16"]
subnet1 = "Dev-subnet1"
address_prefixes1 = ["10.0.1.0/24"]
subnet2 = "Dev-subnet2"
address_prefixes2 = ["10.0.2.0/24"]
nsg = "Dev-sng"
Dev-nic = "Dev-nic"
Dev-vm = "Dev-vm"
